# Generated by Django 5.1.7 on 2025-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lab', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('mecânica', 'Mecânica'), ('informática', 'Informática'), ('química', 'Química')], max_length=15)),
                ('capacidade', models.IntegerField()),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('comum', 'Comum')], default='comum', max_length=20)),
            ],
        ),
    ]
