# Generated by Django 5.1.7 on 2025-04-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='observacao',
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
