# Generated by Django 5.1.7 on 2025-04-23 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sala_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='sala',
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='nome_lab',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='status',
        ),
        migrations.AddField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.laboratorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='capacidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='localizacao',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
