# Generated by Django 5.1.7 on 2025-04-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reserva_options_remove_reserva_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comum', 'Usuário Comum')], default='comum', max_length=10),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
