# Generated by Django 5.1.7 on 2025-04-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_reserva_sala_rename_nome_lab_laboratorio_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='tipo',
            field=models.CharField(choices=[('informatica', 'Laboratório de Informática'), ('sala_aula', 'Sala de Aula'), ('outro', 'Outro')], default='informatica', max_length=20),
        ),
    ]
