# Generated by Django 5.1.7 on 2025-04-15 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_laboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.CharField(max_length=50)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='capacidade',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='tipo',
            field=models.CharField(choices=[('mecânica', 'Mecânica'), ('informática', 'Informática'), ('química', 'Química')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno'), ('admin', 'Administrador')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('cancelada', 'Cancelada')], max_length=10)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.laboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
                ('status_anterior', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('cancelada', 'Cancelada')], max_length=10)),
                ('status_novo', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('cancelada', 'Cancelada')], max_length=10)),
                ('usuario_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reserva')),
            ],
        ),
    ]
